name: Terraform Azure CI/CD

on:
  push:
    branches:
      - feature/rg_sum
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:

  terraform-check:
    name: Terraform Format, Validate, Scan & Plan
    if: github.ref != 'refs/heads/main'
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./Parent_Module
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./Parent_Module
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ./Parent_Module
        run: terraform validate

      - name: Terraform Security Scan
        working-directory: ./Parent_Module
        run: tfsec .

      - name: Terraform Plan
        working-directory: ./Parent_Module
        run: terraform plan


  terraform-apply:
    name: Terraform Apply
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./Parent_Module
        run: terraform init

      - name: Terraform Apply
        working-directory: ./Parent_Module
        run: terraform apply -auto-approve